In [1]:
import numpy as np 

In [2]:
dataset = np.loadtxt("../data/lab2/phoneme.csv", delimiter=',')

# TODO: perform a shape / validity check.
print(dataset.shape)

# TODO:
X = dataset[:, :-1]
y = dataset[:, -1]

(5404, 6)


In [6]:
dataset

array([[ 1.24 ,  0.875, -0.205, -0.078,  0.067,  0.   ],
       [ 0.268,  1.352,  1.035, -0.332,  0.217,  0.   ],
       [ 1.567,  0.867,  1.3  ,  1.041,  0.559,  0.   ],
       ...,
       [ 1.031,  0.584,  1.866,  1.532, -0.671,  1.   ],
       [ 0.15 ,  0.933,  2.363, -0.742, -0.617,  0.   ],
       [ 0.137,  0.714,  1.35 ,  0.972, -0.63 ,  1.   ]])

In [4]:
X

array([[ 1.24 ,  0.875, -0.205, -0.078,  0.067],
       [ 0.268,  1.352,  1.035, -0.332,  0.217],
       [ 1.567,  0.867,  1.3  ,  1.041,  0.559],
       ...,
       [ 1.031,  0.584,  1.866,  1.532, -0.671],
       [ 0.15 ,  0.933,  2.363, -0.742, -0.617],
       [ 0.137,  0.714,  1.35 ,  0.972, -0.63 ]])

In [5]:
y

array([0., 0., 0., ..., 1., 0., 1.])

In [9]:
ex = np.array([[1,2, 3], [5, 3,4], [8,9,7]])

ex

array([[1, 2, 3],
       [5, 3, 4],
       [8, 9, 7]])

In [17]:
ex[:, :2]

array([[1, 2],
       [5, 3],
       [8, 9]])

In [18]:
len(X)

5404

implementar diretamente aqui o modelo para ir experimentando diferentes parameters e criar um bom modelo